server:
  port: 8087

spring:
  application:
    name: exchange-quotation-service
  datasource:
    url: jdbc:mysql://localhost:3306/exchange?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver