server:
  port: 10001

spring:
  application:
    name: exchange-user-service
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/exchangedb?useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

